version: "1.0"
name: "default"
description: "Baseline enterprise-safe policy pack"

rules:
  pii:
    enabled: true
    redact: true
    allow_when_classification: ["PUBLIC", "INTERNAL"]
    block_when_classification: ["RESTRICTED"]
  secrets:
    enabled: true
    redact: true
    block_when_classification: ["RESTRICTED"]
  no_sensitive_echo:
    enabled: true
